# Generated by Django 5.2 on 2025-05-06 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comprobante', models.CharField(choices=[('01', 'Factura'), ('03', 'Boleta')], max_length=2)),
                ('serie', models.CharField(max_length=4)),
                ('correlativo', models.CharField(max_length=6)),
                ('estado_sunat', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('observado', 'Observado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='comprobantes/pdf/')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.venta')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_producto', models.CharField(choices=[('accesorio', 'Accesorio'), ('montura', 'Montura'), ('luna', 'Luna')], max_length=10)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='comprobantes.comprobante')),
                ('producto_accesorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.accesorio')),
                ('producto_luna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.luna')),
                ('producto_montura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.montura')),
            ],
        ),
    ]
