# Generated by Django 5.2 on 2025-05-07 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='correlativo',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='serie',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
