# Generated by Django 5.2 on 2025-06-01 20:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0006_rename_recdip_receta_recdipcerca_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('emplCod', models.AutoField(primary_key=True, serialize=False)),
                ('emplNom', models.CharField(max_length=50)),
                ('emplCarg', models.CharField(choices=[('gerente', 'Gerente'), ('colaborador', 'Colaborador')], max_length=20)),
                ('empCond', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Luna',
            fields=[
                ('lunaCod', models.AutoField(primary_key=True, serialize=False)),
                ('lunaProp', models.CharField(choices=[('blue', 'Blue'), ('fotocromatico', 'Fotocromatico'), ('blue_fotocromatico', 'Blue Fotocromatico'), ('ar', 'AR')], max_length=50)),
                ('lunaMat', models.CharField(choices=[('policarbonato', 'Policarbonato'), ('nk', 'NK'), ('resina', 'Resina'), ('cristal', 'cristal')], max_length=20)),
                ('lunaColorHalo', models.CharField(choices=[('azul', 'Azul'), ('verde', 'Verde'), ('morado', 'Morado')], max_length=20)),
                ('lunaCosto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lunaPrecioVenta', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('ventNum', models.AutoField(primary_key=True, serialize=False)),
                ('venFecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('venTipoPago', models.CharField(choices=[('efectivo', 'Efectivo'), ('credito', 'Credito'), ('debito', 'Debito')])),
                ('venEstado', models.CharField(choices=[('adelanto', 'Adelanto'), ('proceso', 'Proceso'), ('cancelado', 'Cancelado')])),
                ('venSaldoRes', models.FloatField(null=True)),
                ('cliCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='cliente.cliente')),
                ('empCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='ventas.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('detVenCantidad', models.PositiveIntegerField()),
                ('detVenValorUni', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detVenSubtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('detVenDescr', models.CharField(max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('ventNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta')),
            ],
        ),
        migrations.CreateModel(
            name='BoletaElectronica',
            fields=[
                ('boletNum', models.IntegerField(primary_key=True, serialize=False)),
                ('boletSerie', models.CharField(max_length=10)),
                ('boletCorrelat', models.CharField(max_length=20)),
                ('boleFech', models.DateField()),
                ('boleTipoDoc', models.CharField(choices=[('B', 'Boleta'), ('F', 'Factura')], max_length=1)),
                ('boleEstadoEnvio', models.CharField(choices=[('N', 'No enviada'), ('P', 'En proceso'), ('E', 'Enviada')], max_length=1)),
                ('ventNum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boleta_de_venta', to='ventas.venta')),
            ],
        ),
    ]
