# Generated by Django 5.2 on 2025-05-27 04:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0005_rename_clinum_cliente_clinumcel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('emplCod', models.AutoField(primary_key=True, serialize=False)),
                ('emplNom', models.CharField(max_length=50)),
                ('emplCarg', models.CharField(max_length=20)),
                ('empUsua', models.CharField(max_length=40)),
                ('empContr', models.CharField(max_length=8)),
                ('empCond', models.CharField(choices=[('Activo', 'activo'), ('Inactivo', 'inactivo')])),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('ventNum', models.AutoField(primary_key=True, serialize=False)),
                ('venFecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('venTipoPago', models.CharField(choices=[('Efectivo', 'efectivo'), ('Credito', 'credito'), ('Debito', 'Debito')])),
                ('venEstado', models.CharField(choices=[('Pendiente parcial', 'pendiente parcial'), ('Proceso', 'proceso'), ('Cancelado', 'cancelado')])),
                ('venSaldoRes', models.FloatField(null=True)),
                ('cliCod', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='cliente.cliente')),
                ('empCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='ventas.empleado')),
            ],
        ),
    ]
