# Generated by Django 5.2 on 2025-06-02 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemboleta',
            name='boleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.boleta'),
        ),
        migrations.AlterField(
            model_name='itemboleta',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='itemboleta',
            name='object_id',
            field=models.CharField(max_length=100),
        ),
    ]
