# Generated by Django 5.2 on 2025-05-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='venEstado',
            field=models.CharField(choices=[('Adelanto', 'adelanto'), ('Proceso', 'proceso'), ('Cancelado', 'cancelado')]),
        ),
        migrations.AlterField(
            model_name='venta',
            name='venTipoPago',
            field=models.CharField(choices=[('Efectivo', 'efectivo'), ('Credito', 'credito'), ('Debito', 'debito')]),
        ),
    ]
