# Generated by Django 5.2 on 2025-06-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_venta_venestado_alter_venta_ventipopago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='venEstado',
            field=models.CharField(choices=[('adelanto', 'Adelanto'), ('proceso', 'Proceso'), ('cancelado', 'Cancelado')]),
        ),
        migrations.AlterField(
            model_name='venta',
            name='venTipoPago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('credito', 'Credito'), ('debito', 'Debito')]),
        ),
    ]
