# Generated by Django 5.2 on 2025-06-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_itemboleta_boleta_alter_itemboleta_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='estado',
            field=models.CharField(default='pendiente', max_length=20),
        ),
    ]
