# Generated by Django 5.2 on 2025-06-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_venta_venestado_alter_venta_ventipopago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cliNumDoc', models.CharField(max_length=20, unique=True, verbose_name='Número de Documento')),
                ('cliNom', models.CharField(max_length=100, verbose_name='Nombre')),
                ('cliNumCel', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('cliEmail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'venta_cliente',
            },
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='ventNum',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cliCod',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='empCod',
        ),
        migrations.DeleteModel(
            name='BoletaElectronica',
        ),
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
