# Generated by Django 5.2 on 2025-06-02 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_boleta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemboleta',
            name='boleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.boleta'),
        ),
    ]
