# Generated by Django 5.2 on 2025-06-22 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ventas', '0005_itemboleta_descripcion_personalizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemboleta',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='itemboleta',
            name='object_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='itemboleta',
            table='ventas_itemboleta',
        ),
    ]
