# Generated by Django 5.2 on 2025-06-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_alter_itemboleta_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='codigo_sunat',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='boleta',
            name='enviado_sunat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boleta',
            name='fecha_envio_sunat',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boleta',
            name='hash_sunat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='boleta',
            name='mensaje_sunat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boleta',
            name='nombre_cdr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
