# Generated by Django 5.2 on 2025-06-29 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_boleta_codigo_sunat_boleta_enviado_sunat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='empCond',
            new_name='emplCond',
        ),
    ]
