# Generated by Django 5.2 on 2025-07-06 22:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_boleta_codigo_sunat_boleta_enviado_sunat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoAdelanto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('deposito', 'Depósito'), ('cheque', 'Cheque')], default='efectivo', max_length=20)),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adelantos', to='ventas.boleta')),
            ],
            options={
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
