# Generated by Django 5.2 on 2025-06-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_emplcod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuarioNom',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
