# Generated by Django 5.2 on 2025-05-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_doc', models.CharField(choices=[('1', 'DNI'), ('6', 'RUC')], max_length=1)),
                ('num_doc', models.CharField(max_length=11, unique=True)),
                ('rzn_social', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
