# Generated by Django 5.2 on 2025-06-01 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('ventas', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='emplCod',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='ventas.empleado'),
        ),
    ]
