# Generated by Django 5.2 on 2025-06-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('proCod', models.AutoField(primary_key=True, serialize=False)),
                ('proNombre', models.CharField(max_length=100)),
                ('proTipo', models.CharField(max_length=50)),
                ('proCosto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proPrecioVenta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accDescrip', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Montura',
            fields=[
                ('proCod', models.AutoField(primary_key=True, serialize=False)),
                ('proNombre', models.CharField(max_length=100)),
                ('proTipo', models.CharField(max_length=50)),
                ('proCosto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proPrecioVenta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monMarca', models.CharField(choices=[('zetti', 'Zetti'), ('fiorella_conte', 'Fiorella Conte'), ('ferioni', 'Ferioni')], max_length=50)),
                ('monPubl', models.CharField(choices=[('mujer_clasico', 'Mujer Clasico'), ('mujer_tendencia', 'Mujer Tendencia'), ('niño', 'Niño'), ('Varon_clasico', 'Varon Clasico'), ('varon_tendencia', 'Varon Tendencia')], max_length=25)),
                ('monMate', models.CharField(choices=[('M', 'Metal'), ('P', 'Plástico'), ('A', 'Acetato'), ('C', 'Carey'), ('TR', 'TR')], max_length=25)),
                ('monColor', models.CharField(choices=[('rojo', 'Rojo'), ('negro', 'Negro'), ('animal-print', 'Animal-Print'), ('blanco', 'Blanco'), ('rosa', 'Rosa'), ('nude', 'Nude'), ('verde', 'Verde'), ('azul', 'Azul'), ('dorado', 'Dorado'), ('plateado', 'Plateado'), ('transparente', 'Transparente'), ('plomo', 'Plomo')], default='negro', max_length=25)),
                ('monVendida', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
