# Generated by Django 5.2 on 2025-05-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('proCod', models.AutoField(primary_key=True, serialize=False)),
                ('proNombre', models.CharField(max_length=100)),
                ('proTipo', models.CharField(max_length=50)),
                ('proPrecioCompra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proPrecioVenta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accDescrip', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Luna',
            fields=[
                ('proCod', models.AutoField(primary_key=True, serialize=False)),
                ('proNombre', models.CharField(max_length=100)),
                ('proTipo', models.CharField(max_length=50)),
                ('proPrecioCompra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proPrecioVenta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lunaProp', models.CharField(choices=[('blue', 'Blue'), ('fotocromatico', 'Fotocromatico'), ('blue_fotocromatico', 'Blue Fotocromatico'), ('ar', 'AR')], max_length=50)),
                ('lunaMat', models.CharField(choices=[('policarbonato', 'Policarbonato'), ('nk', 'NK'), ('resina', 'Resina'), ('cristal', 'cristal')], max_length=20)),
                ('lunaColorHalo', models.CharField(choices=[('azul', 'Azul'), ('verde', 'Verde'), ('morado', 'Morado')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Montura',
            fields=[
                ('proCod', models.AutoField(primary_key=True, serialize=False)),
                ('proNombre', models.CharField(max_length=100)),
                ('proTipo', models.CharField(max_length=50)),
                ('proPrecioCompra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proPrecioVenta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monMarca', models.CharField(choices=[('zetti', 'Zetti'), ('fiorella_conte', 'Fiorella Conte'), ('ferioni', 'Ferioni')], max_length=50)),
                ('monPublico', models.CharField(choices=[('mujer_clasico', 'Mujer Clasico'), ('mujer_tendencia', 'Mujer Tendencia'), ('niño', 'Niño'), ('Varon_clasico', 'Varon Clasico'), ('varon_tendencia', 'Varon Tendencia')], max_length=25)),
                ('monMaterial', models.CharField(choices=[('metal', 'Metal'), ('plastico', 'Plástico'), ('acetato', 'Acetato'), ('carey', 'Carey'), ('tr', 'TR')], max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
