# Generated by Django 5.2 on 2025-05-27 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesorio',
            old_name='proPrecioCompra',
            new_name='proCosto',
        ),
        migrations.RenameField(
            model_name='luna',
            old_name='proPrecioCompra',
            new_name='proCosto',
        ),
        migrations.RenameField(
            model_name='montura',
            old_name='monMaterial',
            new_name='monMate',
        ),
        migrations.RenameField(
            model_name='montura',
            old_name='monPublico',
            new_name='monPubl',
        ),
        migrations.RenameField(
            model_name='montura',
            old_name='proPrecioCompra',
            new_name='proCosto',
        ),
    ]
