# Generated by Django 5.2 on 2025-06-01 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesorio',
            old_name='proCod',
            new_name='accCod',
        ),
        migrations.RenameField(
            model_name='accesorio',
            old_name='proNombre',
            new_name='accNombre',
        ),
        migrations.RenameField(
            model_name='accesorio',
            old_name='accDescrip',
            new_name='proDescrip',
        ),
        migrations.RemoveField(
            model_name='accesorio',
            name='proTipo',
        ),
        migrations.RemoveField(
            model_name='montura',
            name='proCod',
        ),
        migrations.RemoveField(
            model_name='montura',
            name='proNombre',
        ),
        migrations.RemoveField(
            model_name='montura',
            name='proTipo',
        ),
        migrations.AddField(
            model_name='accesorio',
            name='proStock',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='montura',
            name='monCod',
            field=models.CharField(default=1, max_length=10, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='montura',
            name='proDescrip',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='montura',
            name='proStock',
            field=models.IntegerField(default=1),
        ),
    ]
