# Generated by Django 5.2 on 2025-06-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesorio',
            name='proStock',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='montura',
            name='proStock',
            field=models.IntegerField(default=100),
        ),
    ]
