# Generated by Django 5.2 on 2025-06-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_accesorio_prostock_alter_montura_prostock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='montura',
            name='monMate',
            field=models.CharField(choices=[('Metal', 'Metal'), ('Plastico', 'Plástico'), ('Acetato', 'A'), ('Carey', 'Carey'), ('TR', 'TR')], max_length=25),
        ),
    ]
