# Generated by Django 5.2 on 2025-06-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_rename_propreciocompra_accesorio_procosto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesorio',
            old_name='proCod',
            new_name='accCod',
        ),
        migrations.RenameField(
            model_name='accesorio',
            old_name='proNombre',
            new_name='accNombre',
        ),
        migrations.RenameField(
            model_name='luna',
            old_name='proCod',
            new_name='lunaCod',
        ),
        migrations.RemoveField(
            model_name='accesorio',
            name='proTipo',
        ),
        migrations.RemoveField(
            model_name='luna',
            name='proNombre',
        ),
        migrations.RemoveField(
            model_name='luna',
            name='proTipo',
        ),
        migrations.RemoveField(
            model_name='montura',
            name='proCod',
        ),
        migrations.RemoveField(
            model_name='montura',
            name='proNombre',
        ),
        migrations.RemoveField(
            model_name='montura',
            name='proTipo',
        ),
        migrations.AddField(
            model_name='montura',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='montura',
            name='monCod',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='montura',
            name='monMate',
            field=models.CharField(choices=[('M', 'Metal'), ('P', 'Plástico'), ('A', 'Acetato'), ('C', 'Carey'), ('TR', 'TR')], max_length=25),
        ),
    ]
