# Generated by Django 5.2 on 2025-05-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_rename_propreciocompra_accesorio_procosto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesorio',
            options={'verbose_name': 'Accesorio', 'verbose_name_plural': 'Accesorios'},
        ),
        migrations.AlterModelOptions(
            name='luna',
            options={'verbose_name': 'Luna', 'verbose_name_plural': 'Lunas'},
        ),
        migrations.AlterModelOptions(
            name='montura',
            options={'verbose_name': 'Montura', 'verbose_name_plural': 'Monturas'},
        ),
        migrations.AddField(
            model_name='accesorio',
            name='proActivo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accesorio',
            name='proStock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='luna',
            name='proActivo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='luna',
            name='proStock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='montura',
            name='proActivo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='montura',
            name='proStock',
            field=models.IntegerField(default=0),
        ),
    ]
