# Generated by Django 5.2 on 2025-06-01 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_accesorio_options_alter_luna_options_and_more'),
        ('inventario', '0003_rename_procod_accesorio_acccod_and_more'),
    ]

    operations = [
    ]
