# Generated by Django 5.2 on 2025-07-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_montura_monmate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='montura',
            name='monCod',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
