# Generated by Django 5.2 on 2025-06-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_rename_procod_accesorio_acccod_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesorio',
            old_name='accDescrip',
            new_name='proDescrip',
        ),
        migrations.AddField(
            model_name='luna',
            name='proDescrip',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='montura',
            name='monColor',
            field=models.CharField(choices=[('rojo', 'Rojo'), ('negro', 'Negro'), ('animal-print', 'Animal-Print'), ('blanco', 'Blanco'), ('rosa', 'Rosa'), ('nude', 'Nude'), ('verde', 'Verde'), ('azul', 'Azul'), ('dorado', 'Dorado'), ('plateado', 'Plateado'), ('transparente', 'Transparente'), ('plomo', 'Plomo')], default='negro', max_length=25),
        ),
        migrations.AddField(
            model_name='montura',
            name='monVendida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='montura',
            name='proDescrip',
            field=models.TextField(blank=True, null=True),
        ),
    ]
