# Generated by Django 5.2 on 2025-06-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_merge_20250531_2332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesorio',
            options={},
        ),
        migrations.AlterModelOptions(
            name='luna',
            options={},
        ),
        migrations.AlterModelOptions(
            name='montura',
            options={},
        ),
        migrations.RemoveField(
            model_name='accesorio',
            name='proActivo',
        ),
        migrations.RemoveField(
            model_name='accesorio',
            name='proStock',
        ),
        migrations.RemoveField(
            model_name='luna',
            name='proActivo',
        ),
        migrations.RemoveField(
            model_name='luna',
            name='proStock',
        ),
        migrations.RemoveField(
            model_name='montura',
            name='id',
        ),
        migrations.RemoveField(
            model_name='montura',
            name='proActivo',
        ),
        migrations.RemoveField(
            model_name='montura',
            name='proStock',
        ),
        migrations.AlterField(
            model_name='montura',
            name='monCod',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
