# Generated by Django 5.2 on 2025-06-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_rename_accdescrip_accesorio_prodescrip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='montura',
            name='monCod',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
