# Generated by Django 5.2 on 2025-06-01 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_montura_moncod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Luna',
        ),
    ]
