# Generated by Django 5.2 on 2025-06-01 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_rename_accdescrip_accesorio_prodescrip_and_more'),
        ('inventario', '0005_alter_accesorio_options_alter_luna_options_and_more'),
    ]

    operations = [
    ]
