# Generated by Django 5.2 on 2025-06-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_delete_luna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='montura',
            name='id',
        ),
        migrations.AlterField(
            model_name='montura',
            name='monCod',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
