# Generated by Django 5.2 on 2025-06-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_merge_20250601_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='montura',
            name='monCod',
            field=models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
