# Generated by Django 5.2 on 2025-06-01 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_montura_moncod'),
        ('inventario', '0007_alter_montura_moncod'),
    ]

    operations = [
    ]
