# Generated by Django 5.2 on 2025-05-07 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luna',
            name='halo',
            field=models.CharField(choices=[('azul', 'Azul'), ('verde', 'Verde')], max_length=20),
        ),
        migrations.AlterField(
            model_name='luna',
            name='material',
            field=models.CharField(choices=[('policarbonato', 'Policarbonato'), ('nk', 'NK'), ('resina', 'Resina')], max_length=20),
        ),
        migrations.AlterField(
            model_name='luna',
            name='tipo',
            field=models.CharField(choices=[('monocromatico blue', 'Monocromatico Blue'), ('ar', 'AR'), ('fotocromatico', 'Fotocromatico')], max_length=20),
        ),
        migrations.AlterField(
            model_name='montura',
            name='material',
            field=models.CharField(choices=[('acetato', 'Acetato'), ('acero de moneda', 'Acero de Moneda'), ('carey', 'Carey'), ('metal', 'Metal'), ('plastico', 'Plástico'), ('tr', 'TR'), ('otro', 'Otro')], max_length=20),
        ),
    ]
