# Generated by Django 5.2 on 2025-05-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_luna_halo_alter_luna_material_alter_luna_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesorio',
            name='descripcion',
            field=models.TextField(default='Sin descripción'),
        ),
        migrations.AddField(
            model_name='luna',
            name='descripcion',
            field=models.TextField(default='Sin descripción'),
        ),
        migrations.AddField(
            model_name='montura',
            name='descripcion',
            field=models.TextField(default='Sin descripción'),
        ),
    ]
