# Generated by Django 5.2 on 2025-05-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliCod', models.AutoField(primary_key=True, serialize=False)),
                ('cliNombComp', models.CharField(max_length=50)),
                ('cliNum', models.CharField(max_length=9)),
            ],
        ),
    ]
