# Generated by Django 5.2 on 2025-05-08 17:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cliNumDni',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='edad',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliNum',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rectOpt', models.BooleanField(default=False)),
                ('recfecha', models.DateField(default=django.utils.timezone.now)),
                ('recOD_sph', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('recOD_cyl', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('recOD_eje', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('recOI_sph', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('recOI_cyl', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('recOI_eje', models.DecimalField(blank=True, decimal_places=3, max_digits=3, null=True)),
                ('recDIP', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('recOD_adicion', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('recOI_adicion', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('recObsAdic', models.CharField(blank=True, max_length=50, null=True)),
                ('recCod', models.CharField(editable=False, max_length=50, unique=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='cliente.cliente')),
            ],
        ),
    ]
