# Generated by Django 5.2 on 2025-05-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_alter_cliente_cliedad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cliNum',
            new_name='cliNumCel',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='cliNumDni',
            new_name='cliNumDoc',
        ),
        migrations.RenameField(
            model_name='receta',
            old_name='cliente',
            new_name='cliCod',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cliTipoDoc',
            field=models.CharField(choices=[('DNI', 'dni'), ('Pasaporte', 'pasaporte')], default='DNI', max_length=20),
        ),
    ]
