# Generated by Django 5.2 on 2025-06-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_rename_clinum_cliente_clinumcel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='recDIP',
            new_name='recDIPCerca',
        ),
        migrations.RenameField(
            model_name='receta',
            old_name='recOD_adicion',
            new_name='rec_adicion',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='recOI_adicion',
        ),
        migrations.AddField(
            model_name='receta',
            name='recDIPLejos',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
