# Generated by Django 5.2 on 2025-05-08 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_cliente_clinumdni_cliente_edad_alter_cliente_clinum_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='edad',
            new_name='cliEdad',
        ),
    ]
