# Generated by Django 5.2 on 2025-06-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_rename_recdip_receta_recdipcerca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='recOD_eje',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='recOI_eje',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
