# Generated by Django 5.2 on 2025-06-02 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cliNumDoc', models.CharField(max_length=20, unique=True, verbose_name='Número de Documento')),
                ('cliNom', models.CharField(max_length=100, verbose_name='Nombre')),
                ('cliNumCel', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('cliEmail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'venta_cliente',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('emplCod', models.AutoField(primary_key=True, serialize=False)),
                ('emplNom', models.CharField(max_length=50)),
                ('emplCarg', models.CharField(choices=[('gerente', 'Gerente'), ('colaborador', 'Colaborador')], max_length=20)),
                ('empCond', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Luna',
            fields=[
                ('lunaCod', models.AutoField(primary_key=True, serialize=False)),
                ('lunaProp', models.CharField(choices=[('blue', 'Blue'), ('fotocromatico', 'Fotocromatico'), ('blue_fotocromatico', 'Blue Fotocromatico'), ('ar', 'AR')], max_length=50)),
                ('lunaMat', models.CharField(choices=[('policarbonato', 'Policarbonato'), ('nk', 'NK'), ('resina', 'Resina'), ('cristal', 'cristal')], max_length=20)),
                ('lunaColorHalo', models.CharField(choices=[('azul', 'Azul'), ('verde', 'Verde'), ('morado', 'Morado')], max_length=20)),
                ('lunaCosto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lunaPrecioVenta', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=4)),
                ('correlativo', models.CharField(max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('igv', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ItemBoleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('cantidad', models.IntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.boleta')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
